version: "3"
services:
  db: 
    image: postgres:15
    container_name: db_app
    env_file:
      - .env-non-dev
    ports:
      - "5433:5432"

  posts:
    image: posts_image
    build:
      context: .
    container_name: posts_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
    ports:
      - 9000:8000
        