version: "3"
services:
  web:
    build: .
    container_name: fast_api_app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=localhost  
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=112233
      - DB_NAME=posts
    depends_on:
      - database  

  database: 
    image: "postgres"
    container_name: db-pg
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=112233
    ports:
      - "5440:5432"

        